apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ndp
resources:
- ../base
# - additional-workers.yaml
patchesStrategicMerge:
# - taint.yaml
- exclude-nodes.yaml
- worker-nodes.yaml
# - additional-workers-taint.yaml
# - additional-workers-nodes.yaml