apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-worker-1
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/ilkay-tutorial
        operator: Exists
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fc-worker-2
# spec:
#   template:
#     spec:
#       tolerations:
#       - effect: NoSchedule
#         key: nautilus.io/ilkay-tutorial
#         operator: Exists
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fc-worker-3
# spec:
#   template:
#     spec:
#       tolerations:
#       - effect: NoSchedule
#         key: nautilus.io/ilkay-tutorial
#         operator: Exists
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fc-worker-4
# spec:
#   template:
#     spec:
#       tolerations:
#       - effect: NoSchedule
#         key: nautilus.io/ilkay-tutorial
#         operator: Exists
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fc-worker-5
# spec:
#   template:
#     spec:
#       tolerations:
#       - effect: NoSchedule
#         key: nautilus.io/ilkay-tutorial
#         operator: Exists