apiVersion: v1
kind: Pod
metadata:
  name: fake-api
  labels:
    k8s-app: test-http
spec:
  containers:
  - name: fake-api
    image: gitlab-registry.nrp-nautilus.io/segurvich/test/fake_api_0.0.3
    env:
      - name: DATASETS
        value: "uniform-ensemble,st-mary-large-ensemble"
    resources:
      limits:
        memory: 200Mi
        cpu: 1
      requests:
        memory: 50Mi
        cpu: 1