apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:nautilus-user
  namespace: jupyterlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:nautilus-user
subjects:
- kind: ServiceAccount
  name: default
