apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ndp-test
resources:
- ../base
patchesStrategicMerge:
- exclude-nodes.yaml
- compute-resources.yaml
- worker-node-selector.yaml
- taint.yaml