apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-worker-1
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-RTX-A6000
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8s-a6000-01.calit2.optiputer.net
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                    - us-west
---