# Use an official Jupyter image as a parent image
# More info: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
FROM quay.io/jupyter/minimal-notebook:latest

# Install dependencies
RUN pip install matplotlib pandas transformers torch torchvision torchaudio

# set write persmissions
USER root
RUN mkdir /srv/starter_content/
RUN chown -R jovyan /srv/starter_content/
RUN chown -R jovyan /home/jovyan/

# make sudo access without password
RUN echo 'jovyan ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

WORKDIR /srv/starter_content


# Copy the entrypoint script into the container
COPY entrypoint_clip.sh /entrypoint_clip.sh

# Make the entrypoint script executable
RUN chmod +x /entrypoint_clip.sh

USER jovyan

# Set the entrypoint script as the entrypoint
ENTRYPOINT ["/entrypoint_clip.sh"]
