apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-controller
  labels:
    k8s-app: fc-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fc-controller
  template:
    metadata:
      labels:
        k8s-app: fc-controller
    spec:
      containers:
      - name: fc-controller
        image: segurvich/llm_backend:v0.0.0.1
        command: ["python3"]
        args: ["-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        ports:
          - containerPort: 21001
---
apiVersion: v1
kind: Service
metadata:
  name: fc-controller
spec:
  type: ClusterIP
  ports:
    - port: 21001
      targetPort: 21001
  selector:
    k8s-app: fc-controller