FROM glcr.b-data.ch/jupyterlab/cuda/python/scipy:3.11.5

# Install all needed packages
# RUN conda install -y gcc gxx_linux-64
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install zarr mlflow boto3
# torch zarr mlflow

# Copy starter notebooks, Python files, etc
COPY --chown=jovyan ./starter_content/ /srv/starter_content/