FROM quay.io/jupyter/base-notebook:latest

# Install all needed packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy starter notebooks, Python files, etc
COPY --chown=jovyan ./pgml_starter_content/ /srv/starter_content/