apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-pvc
  namespace: ndp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-cephfs