apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: ndp-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
#  storageClassName: seaweedfs-storage-nvme
  storageClassName: rook-cephfs-central